### ISSUE TITLE
Easy Diffusion v2.5.15 eats up even more memory than before

### ISSUE THREAD

**Issue by tekthy** [easydiffusion/sdkit#15]
Been a user and promoter of Stable Diffusion UI for sometime. I use Nvidia 3050 with 4GB RAM. 
And after the updating to Easy Diffusion v2.5.15, now we cannot generate 512x512 images, saying not enough ram.

**Comment by cmdr2** [comment]
@tekthy Please set the VRAM usage level to "Low".

In Easy Diffusion, please change the "VRAM Usage Level" (in the Settings tab) to "Low". That'll fit quite comfortably inside 4 GB.

Please feel free to drop by our Easy Diffusion discord server, we're happy to help there with further questions: https://discord.com/invite/u9yhsFmEkB
