### ISSUE TITLE
Progress Reporting

### ISSUE THREAD

**Issue by batuhanyus** [easydiffusion/sdkit#26]
Great project!

Any chance to get a progress report/status from generation? Currently generation writes current progress as step/target step to output. It would be good to access this data from API.

**Comment by cmdr2** [comment]
Hi, the progress is reported via a callback in the `generate_images()` function - https://github.com/easydiffusion/sdkit/wiki/API#sdkitgenerate

The `callback` function will be called once per step. It is passed a `torch.Tensor` containing the latents of the image, and an `int` denoting the step index.

For e.g.
```py
def on_step(latent_samples, step_index: int):
    print('step', step_index)

images = generate_images(context, prompt="Astronaut", callback=on_step)
```

Hope that helps!
