### ISSUE TITLE
Add samplers DPM ++ SDE Karras or/and DPM++ 2M Karras

### ISSUE THREAD

**Issue by fedeveloperi81** [easydiffusion/sdkit#27]
Hello, are you planning to add that samplers in the near future?
Regards

**Comment by cmdr2** [comment]
Hi, these are already supported, as mentioned in https://github.com/easydiffusion/sdkit/wiki/Features#image-generation or https://github.com/easydiffusion/sdkit/wiki/API#sdkitgenerate

They're called: `dpmpp_2s_a`, `dpmpp_2m`, `dpmpp_sde`

**Comment by fedeveloperi81** [comment]
Hello, thank you for the answer but as I guess that samplers are samplers DPM ++ SDE and DPM++ 2M but not Karras, or they are and just named that way?
