### ISSUE TITLE
Error Parsing pickle while loading safetensor model.

### ISSUE THREAD

**Issue by cheetahfightfx** [easydiffusion/sdkit#3]
I am using a safetensor model from cvit.com.

I get this error during inference. The image is being generated.

 ERROR MainThread ERROR: parsing pickle in /sd/mytest/models/attractiveWomen_attrMixV2.safetensors: at position 0, opcode b'\x1c' unknown

Also the negative prompts are being ignored since, I have explicitly included nude and nsfw in the negative prompt, but it sometimes generates nude images or nsfw images.

**Comment by cmdr2** [comment]
Hi, can you please try downloading the model again? Or try a different model? It looks like that particular file is corrupt. Thanks

**Comment by cmdr2** [comment]
Also, please try upgrading to the latest sdkit version by using `pip install --upgrade sdkit`.
