### ISSUE TITLE
Ability to load Loras

### ISSUE THREAD

**Issue by martinkaberg** [easydiffusion/sdkit#37]
**Is your feature request related to a problem? Please describe.**
I am not able to load Loras the same way as i am in webui prompt like <lora:NAME-1.1:1>

**Describe the solution you'd like**
Ability to load loras so i can copy paste prompt from webui

**Describe alternatives you've considered**
I have loaded the safe tensor in model_paths.lora  and then  i have called load_model(context, 'lora')

**Additional context**

**Comment by cmdr2** [comment]
Hi @martinkaberg LoRA is currently experimental, so it needs you to enable a `test_diffusers` flag. You can do it like this:

```py
from sdkit import Context
context = Context()
context.test_diffusers = True

# do the usual things like loading models etc
from sdkit.models import load_model

context.model_paths['lora'] = '/path/to/lora.ckpt'
context.model_paths['stable-diffusion'] = '/path/to/sd-model.safetensors'

load_model(context, 'stable-diffusion')
load_model(context, 'lora')
```

After this, your calls to `generate_images()` will use the LoRA as well.

Hope that helps.

Please reopen if it's not working, thanks!

**Comment by cmdr2** [comment]
Also, you cannot include the LoRA path in the prompt. That's specific to A1111, and in sdkit and other engines, you specify the LoRA to use by loading the LoRA model (like I pointed out in the previous message).
