### ISSUE TITLE
Crashing for unknown reason

### ISSUE THREAD

**Issue by ManInDark** [easydiffusion/sdkit#41]
**Describe the bug**
Python crashes after the `load_model(context, "stable-diffusion")` command is run.

**To Reproduce**
1. Install program using https://github.com/cmdr2/stable-diffusion-ui
2. Start the developer console to have the necessary python environment
3. Run the program as outlined in 302-device-run_on_cpu.py

**Expected behavior**
It should not crash, or at least give a meaningful error message.

**Screenshots**
```
Python 3.8.5 | packaged by conda-forge | (default, Sep 24 2020, 16:55:52) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sdkit
>>> from sdkit.generate import generate_images
>>> from sdkit.models import load_model

/home/username/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
No module 'xformers'. Proceeding without it.
>>> context = sdkit.Context()

>>> context.model_paths["stable-diffusion"] = "models/stable-diffusion/sd-v1-4.ckpt"

>>> context.model_paths["stable-diffusion"] = "./models/stable-diffusion/sd-v1-4.ckpt"

>>> context.device = "cpu"

23:51:05.259 INFO MainThread forcing full precision for device: cpu
>>> load_model(context, "stable-diffusion")

23:51:12.023 INFO MainThread loading stable-diffusion model from ./models/stable-diffusion/sd-v1-4.ckpt to device: cpu
23:51:21.159 INFO MainThread using config: /home/username/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/models_db/configs/v1-inference.yaml
23:51:21.178 INFO MainThread using attn_precision: fp32
LatentDiffusion: Running in eps-prediction mode
Getötet
```
As my system is set to German, it says "Getötet" at the end, which means "Killed".

**Environment (please complete the following information):**
 - OS (with OS version): Debian 11
 - Python version: 3.8.5

**Additional context**
If there is anything else that I could try or do to clear up the problem, please tell me.
If the ui is run, it crashes here: [on_sd_start.sh#L89](https://github.com/cmdr2/stable-diffusion-ui/blob/main/scripts/on_sd_start.sh#L89)

**Comment by cmdr2** [comment]
Also, I noticed that you're loading the model to the CPU. That'll force the model to run in fp32, which will consume a lot of RAM.

Unless you really need to do it, I'd advise removing the `context.device = 'cpu'` line.

**Comment by ManInDark** [comment]
Thanks @cmdr2 for the help! I didn't notice the high RAM usage (and the small default swap) but after a quick test it was definitely the problem. I then went with your suggestion, and it now works like a charm. Thank you! Although sadly I have to use `context.device = 'cpu'` since the device does not have a GPU, which is why I am very thankful that there are people making their projects support CPU only users too. Keep up the good work 👍

**Comment by cmdr2** [comment]
Thanks! Glad it works now.
