### ISSUE TITLE
KeyError: 'canny'

### ISSUE THREAD

**Issue by derekcbr** [easydiffusion/sdkit#63]
# convert an existing image into an openpose image (or skip these lines if you have a custom openpose image)
from sdkit.filter import apply_filters

input_image = Image.open("man_pose.jpg")  # set your input image here <---------

openpose_image = apply_filters(context, "openpose", input_image)  # you can apply other filters too, e.g. "canny" etc.

Traceback (most recent call last):

  File C:\ProgramData\anaconda3\envs\pytorch\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\admin\documents\easydiffusion\mysdkit005.py:26
    canny_image = apply_filters(context, "canny", input_image) # you can apply other filters too, e.g. "canny" etc.

  File ~\AppData\Roaming\Python\Python310\site-packages\sdkit\filter\apply_filters.py:39 in apply_filters
    return [apply_filter_single_image(context, filters, image, **kwargs) for image in images]

  File ~\AppData\Roaming\Python\Python310\site-packages\sdkit\filter\apply_filters.py:39 in <listcomp>
    return [apply_filter_single_image(context, filters, image, **kwargs) for image in images]

  File ~\AppData\Roaming\Python\Python310\site-packages\sdkit\filter\apply_filters.py:49 in apply_filter_single_image
    image = get_filter_module(filter_type).apply(context, image, **kwargs)

  File ~\AppData\Roaming\Python\Python310\site-packages\sdkit\filter\apply_filters.py:59 in default_apply
    model = context.models[filter_type]

KeyError: 'canny'

**Comment by cmdr2** [comment]
Hi @derekcbr Thanks for reporting, and sorry for that. The example missed a few lines, I've updated it with the function calls necessary to load the controlnet filter model: https://github.com/easydiffusion/sdkit/commit/f1912b9d2381088c525573f66db77ae180bccb77

Thanks
